#!/bin/bash
echo "フェスタ用swf,swiffyをコピーします. "

if [ $# -ne 2 ]; then
    echo -e "キャンペーンのIDと、PF数を指定してください\nex) cpfestaflash akifes 3"
    exit 1
else
    festa_id=$1
    pf_count=$2
    WORKROOT="$(pwd)"
    echo $WORKROOT
    cd "$WORKROOT"
    ssh bkrs2 sh "~/shells/mkdir_festa.sh $festa_id"

    campaign_file_name="campaign_op0`expr $pf_count - 1`"
    find . -type f -name "*\.swf" | while read f;do
        if [ `echo $f | grep all_clear` ] ; then
            file_name='festa_comp'
        elif [ `echo $f | grep clear` ] ; then
            file_name='festa_quest_clear'
        elif [ `echo $f | grep present` ] ; then
            file_name='festa_present'
        elif [ `echo $f | grep $campaign_file_name` ] ; then
            file_name='festa_start'
        fi

        if [ `echo $f | grep $campaign_file_name` ] ; then
            check_swf $f
            scp -iv $f "amachi@bkrs2:/home/amachi/newtrunk/share/www/bkrs2/resource/flash/festa/"$festa_id"/"$pf_count"/"$file_name".swf"
        elif [ `echo $f | grep campaign_op` ] ; then
            :
        else
            :
#            check_swf $f
#            scp -iv $f "amachi@bkrs2:/home/amachi/newtrunk/share/www/bkrs2/resource/flash/festa/"$festa_id"/"$file_name".swf"
        fi
    done

     find . -type f -name "*\.html" | while read f;do
        sed -i -e '/<style>/,/<\/html>/d' $f
        if [ `echo $f | grep all_clear` ] ; then
            file_name='festa-comp'
            replace_str=`cat <<'EOT'
<style>html, body {width: 100%; height: 100%; background-color:#f0f0f0;}</style>
</head>
<body style="margin: 0; overflow: hidden;">
<div id="stage" onClick="jump()">
<div id="swiffycontainer" style="width: 100%; height: 320px;"></div>
</div>
<script>
var stage = new swiffy.Stage(document.getElementById('swiffycontainer'), swiffyobject);
stage.start();
stage.setFlashVars("tx1=<?= $this->params['tx1']?>");
stage.setFlashVars("tx2=<?= $this->params['tx2']?>");
stage.setFlashVars("tx3=<?= $this->params['tx3']?>");
stage.setFlashVars("appli=<?= $this->params['appli'] ?>");
var cnt = 0;
function jump(){
    cnt++;
    if (cnt == 4){
        location.replace('<?= $this->next_url ?>');
    }
}
</script>
</body>
</html>
EOT`
        elif [ `echo $f | grep clear` ] ; then
            file_name='festa-quest-clear'
            replace_str=`cat <<'EOT'
<style>html, body {width: 100%; height: 100%; background-color:#f0f0f0;}</style>
</head>
<body style="margin: 0; overflow: hidden;">
<div id="stage" onClick="jump()">
<div id="swiffycontainer" style="width: 100%; height: 320px;"></div>
</div>
<script>
var stage = new swiffy.Stage(document.getElementById('swiffycontainer'), swiffyobject);
stage.start();
stage.setFlashVars("tx1=<?= $this->params['tx1']?>");
stage.setFlashVars("appli=<?= $this->params['appli'] ?>");
function jump(){
        location.replace('<?= $this->next_url ?>');
}
</script>
</body>
</html>
EOT`

        elif [ `echo $f | grep present` ] ; then
            file_name='festa-present'
            replace_str=`cat <<'EOT'
<style>html, body {width: 100%; height: 100%; background-color:#f0f0f0;}</style>
</head>
<body style="margin: 0; overflow: hidden;">
<div id="stage" onClick="jump()">
<div id="swiffycontainer" style="width: 100%; height: 320px;"></div>
</div>
<script>
var stage = new swiffy.Stage(document.getElementById('swiffycontainer'), swiffyobject);
stage.start();
stage.setFlashVars("tx1=<?= $this->params['tx1']?>");
stage.setFlashVars("appli=<?= $this->params['appli'] ?>");
function jump(){
    location.replace('<?= $this->next_url ?>');
}
</script>
</body>
</html>
EOT`

        elif [ `echo $f | grep $campaign_file_name` ] ; then
            file_name='festa-start'
            replace_str=`cat <<'EOT'
<style>html, body {width: 100%; height: 100%; background-color:#f0f0f0;}</style>
</head>
<body style="margin: 0; overflow: hidden;">
<div id="swiffycontainer" style="width: 100%; height: 320px;"></div>
<script>
var stage = new swiffy.Stage(document.getElementById('swiffycontainer'), swiffyobject);
stage.start();
stage.setFlashVars("appli=<?= $this->params['appli'] ?>");
stage.setFlashVars("next_uri=<?= $this->next_url?>");
</script>
</body>
</html>
EOT`

        fi

        sed -i -e '/<style>/,/<\/html>/d' $f
        echo "$replace_str" | while read line
        do
            echo $line >> $f
        done

        if [ `echo $f | grep $campaign_file_name` ] ; then
            scp -iv $f "amachi@bkrs2:/home/amachi/newtrunk/share/www/bkrs2/application/modules/main/views/scripts/gimmick/html/festa/"$festa_id"/"$pf_count"/"$file_name".phtml"
        elif [ `echo $f | grep campaign_op` ] ; then
            :
        else
            :
#            scp -iv $f "amachi@bkrs2:/home/amachi/newtrunk/share/www/bkrs2/application/modules/main/views/scripts/gimmick/html/festa/"$festa_id"/"$file_name".phtml"
        fi

     done

    ssh bkrs2 sh "~/shells/chmod.sh festa"
fi
