#!/bin/sh
# findstr [ -iv ] string [ filename ]
# -i 大文字、小文字の区別をしない
# -v 文字列も出力

CMDNAME='basename $0'
USAGE="USAGE : $CMDNAME [foldername] string"
STRING=
FOLDER=
I=
L=-1

if [ "$OPTIND" = 1 ];then
    while getopts iv: OPT
    do
        case $OPT in
            i) I=-i ;;
            v) L=
                ;;
            ¥?) echo "$USAGE" 1>&2
                exit 1
                ;;
        esac
    done
    shift `expr $OPTIND - 1`
else
    while :
    do
        case $1 in
            -i) I=-i
                shift
                ;;
            -v) L=
                shift
                ;;
            --) shift
                break
                ;;
            -*) echo "$USAGE" 1>&2
                exit 1
                ;;
            *)  break
                ;;
        esac
    done
fi

# if [ $# -lt 1 -o $# -gt 2 ];then
#     echo "$USAGE" 1>&2
#     exit 1
# fi

FOLDER=$1
STRING=$2
#find "$FOLDER" \( -name ".svn" \) -prune -o -type f  -print | xargs -e grep $I "$STRING" /dev/null
# find "$FOLDER" \( -name ".svn" \) -prune -o -type f -regex ".*[^svn|git|svn\-base]" -print | xargs -e grep $I "$STRING" /dev/null
#find "$FOLDER" \( -name ".svn" \) -prune -o -type f -regex ".*[^svn|git|svn\-base]" -print | xargs grep $I "$STRING" /dev/null

find . \( -name ".svn" \) -prune -o -type f -exec grep $I $L "$STRING" {} /dev/null \;
#    -type f -exec grep $I $L "$STRING" {} /dev/null \;
