#!/bin/bash
echo -n "system_360pngをコピーしますか? [y/n] : "
read y

if [ $y = 'y' -o $y = 'yes' ]
then
    cd "アイテム/system_360png"
    #cd "./system_360png"
    #cd "アイテム/system_item"
    find . -type f -name "*\.png" | while read f;do
        echo $f
        scp $f amachi@bkrs2:/home/amachi/newtrunk/bin/bkrs2/master/image/item/$f
    done
    ssh bkrs2 sh "~/shells/mkphp.sh item"
    wait
else
    echo 'Bye'
    exit 0
fi
