#!/bin/bash
echo "アイテムフォルダ以下の料理画像をコピー => i or item\n"
echo "カレントフォルダ以下の料理画像をコピー => c or current :"
read y

if [ $y = 'i' -o $y = 'item' ];then
    folder="アイテム/system_料理"
elif [ $y = 'c' -o $y = 'current' ]
then
    folder="system_料理"
fi

if [ "$folder" ];then
    files=""
    for f in ${folder}'/'[0-9]*.png
    do
        files="${files} ${f}"
    done
    scp $files amachi@bkrs2:~/newtrunk/bin/bkrs2/master/image/food/
    echo "$files をコピーしました"

    ssh bkrs2 sh "~/shells/mkphp.sh food"
    wait
else
    echo 'Bye'
    exit 0
fi

