#!/bin/sh
# sp - set project
# プロジェクトフォルダを変更
# それっぽいフォルダを選択し、移動を

while getopts h: OPT
do
    case $OPT in
        h)  echo $str"プロジェクトフォルダを変えます。フォルダが特定できる最低限の条件で検索します。Usage : sp プロジェクトフォルダ名のヒント" 1>&2 ;;
        \?) echo "Usage : sp プロジェクトフォルダ名のヒント" 1>&2
            exit 1 ;;
    esac
done


if [ "$1" ]; then
    for f in ${HOME}'/'${1}*
    do
        export PROJ=$f
        break
    done
else
    export PROJ="$HOME/newtrunk"
fi
echo "プロジェクトフォルダは $PROJ に移動しました"

export VIEWS="$PROJ/share/www/bkrs2/application/modules/main/views/"
export CONTR="$PROJ/share/www/bkrs2/application/modules/main/controllers/"
export TOOL="$PROJ/share/www/bkrs2-tool/application/modules/main/"
export IMAGE="$PROJ/share/www/img/public/img/"
export SY="$PROJ/lib/php/Synphonie/Bkrs2/"
export MODEL="$PROJ/lib/php/Synphonie/Bkrs2/Master/"
export SY_LOG="$PROJ/logs/bkrs2/gree/"

alias cdh="cd ${PROJ}"               # home
alias cdv="cd ${VIEWS}" # view
alias cds="cd ${VIEWS}scripts" # view
alias cdc="cd ${CONTR}"         # controller
alias cdf="cd ${SY}"            # framework
alias cdt="cd ${TOOL}"         # bkrs2-tool
alias cdi="cd ${IMAGE}"         # bkrs2-tool
alias cdr="cd $PROJ/share/www/bkrs2/resource/"         # resource
alias cdr="cd $PROJ/share/www/bkrs2/resource/"         # resource

# エラーログやシステムログをtailで見る(デフォルト30行)
alias debug="tail -f -n 100 ${SY_LOG}zend/zend.log"
alias aerror="tail -f -n 100 ${SY_LOG}apache/error.log"
alias aaccess="tail -f -n 100 ${SY_LOG}apache/$1.log"

# cacheを消すための変数を設定
# http://redmine.dev.synphonie.com/projects/bkrs2/wiki/%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5%E6%93%8D%E4%BD%9C
export SY=$PROJ
export PERL5LIB=$SY/framework/perl:$SY/lib/perl
export SYNPHONIE_HOME=$SY
export SERVICE_ID=bkrs2
export PROVIDER_ID=gree
export APPLICATION_ENV=devel

#プロジェクトのルートフォルダへ移動
cdh
